# Generated by Django 5.0 on 2024-03-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_product_desc_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
